# プロジェクト設定
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# バージョン情報 (26.2 向けの架空のビルド番号を含む)
minecraft_version=26.2
yarn_mappings=26.2+build.1:v2
loader_version=0.16.0
fabric_version=0.100.0+26.2

# Voice Chat APIバージョン
voicechat_api_version=2.5.0

mod_version=1.0.0
maven_group=net.azarasi
archives_base_name=ytvc
